apiVersion: v1
kind: Service
metadata:
  name: bmi-react-service
  namespace: argocd
spec:
  selector:
    app: bmi-react
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
  type: NodePort