apiVersion: v1
kind: Service
metadata:
  name: bmi-react-service
  namespace: argocd
spec:
  selector:
    app: bmi-react
  ports:
    - protocol: TCP
      port: 33333
      targetPort: 31222
  type: NodePort